### ISSUE TITLE
add a Number of Runtimes option to Planning

### ISSUE THREAD

**Issue by activeeon-bot** [ow2-proactive/agent-windows#212]
<a href="https://jira.activeeon.com/browse/AGENT-213" title="AGENT-213">Original issue</a> created by <a href="mailto:fabien.viale_AT_activeeon.com">Fabien Viale</a> on 26, Feb 2014 at 13:04 PM - AGENT-213

<hr />

It would be useful to set for a Weekly planning, the number of runtimes available. For example, only 1 or 2 runtimes could be available during the day, and the full machine capabilities would be available during the night or week end

**Comment by fviale** [comment]
this was fixed by 120ad35e532d83435004929b4e6586bab1b34f5a (allowing to choose the number of workers in the planning)
