### ISSUE TITLE
Unknown default password during installation

### ISSUE THREAD

**Issue by lpellegr** [ow2-proactive/agent-windows#245]
The installation binary shows by default a window with preconfigured login and password. However, the password that is defined is not known by the user that performs the installation. This password field should be empty by default or its value written in the documentation. The first option seems better from a security point of view.

![capture d ecran de 2015-08-12 11-15-46](https://cloud.githubusercontent.com/assets/128898/9220543/a140025c-40e3-11e5-83bc-b741c9d3a315.png)

**Comment by tobwiens** [comment]
There is a default password in: 
https://github.com/ow2-proactive/agent-windows/blob/master/installer_script.nsi

**Comment by lpellegr** [comment]
@tobwiens Yes but a user will probably not look at the source code since the URL of the repository is not even available from documentation, etc.
