### ISSUE TITLE
ProActive Agent Installation is not working due to password encryption failure

### ISSUE THREAD

**Issue by tobwiens** [ow2-proactive/agent-windows#249]
Used: ProActiveAgent-7.11.0-standalone-x64-setup.exe
Windows Version: 10

What did I do:
Just clicked next in the ProActive Agent installation (default settings)

What happened:
![image](https://cloud.githubusercontent.com/assets/6491363/16297238/4c86908c-3930-11e6-9128-06d908eb263d.png)

**Comment by lpellegr** [comment]
I am getting the same issue on Windows Server 2008 RC2!

**Comment by lpellegr** [comment]
The error message is defined in `installer_script` file. It is displayed if the call to `pacrypt::encryptData(w,w)` returns the value `2`.

**Comment by lpellegr** [comment]
Fixed by #d03aab3bc61ce1b965dab4f22bd453d4892dd9d2.
