### ISSUE TITLE
No Certificate Warning on Windows 10

### ISSUE THREAD

**Issue by tobwiens** [ow2-proactive/agent-windows#250]
When executing the installer, following dialog appears on Windows 10.
<img width="960" alt="2016-07-01 1" src="https://cloud.githubusercontent.com/assets/6491363/16517919/63f292b0-3f80-11e6-833f-3eb5500def5c.png">
After clicking on more info:
<img width="960" alt="2016-06-23" src="https://cloud.githubusercontent.com/assets/6491363/16517920/63f32da6-3f80-11e6-8e80-b0eb05f084ae.png">

**Comment by lpellegr** [comment]
@tobwiens Duplicate of https://github.com/ow2-proactive/agent-windows/issues/244.
