### ISSUE TITLE
GUI editor is not loading JVM properties from PAAgent-config.xml

### ISSUE THREAD

**Issue by lpellegr** [ow2-proactive/agent-windows#253]
ProActive Agent Control features a GUI to edit _PAAgent-config.xml_. Unfortunately, this editor is not loading JVM properties from the file. The main issue is that adding a new property from the GUI erases the following default properties since they are not loaded:

```
<param>-Djava.io.tmpdir=C:\Users\PROACT~1\AppData\Local\Temp\${rank}</param>
<param>-Dpa.logs.home=C:\Users\PROACT~1\AppData\Local\Temp\${rank}</param>
<param>-Dproactive.node.monitoring.db.dir=C:\Users\PROACT~1\AppData\Local\Temp\${rank}\</param>
<param>-Dpas.launcher.forkas.method=pwd</param>
```

The current workaround is to edit the file manually which is not obvious for end-users.

**Comment by fviale** [comment]
This seems to be a regression as I don't remember facing such an issue before. Annoying one.
