### ISSUE TITLE
Unable to encrypt the password. Password too long?

### ISSUE THREAD

**Issue by lpellegr** [ow2-proactive/agent-windows#255]
A user has reported an issue with large passwords when creating an account for _proactive_ from the graphical user interface.

The Windows version used was _Windows server 2012_. 

The password was similar in terms of length and kind of characters to `abcDef555ghi@` (13 characters).

**Comment by lpellegr** [comment]
The user noticed that the initial password was a bit longer. He changed the password of the windows account which the nodes will run as. He also uninstalled the community version of the agent prior to starting. This is a potential workaround. 

It would be interesting to know if the length limitation is due to Windows or something related to the implementation of the agent.

**Comment by fviale** [comment]
Is this related to: https://github.com/ow2-proactive/agent-windows/issues/249

**Comment by lpellegr** [comment]
It seems not to be the case. The issue you mention has a really similar error message but from what I remember it was happening for any input value (whatever the password length and kind is). Based on user feedback, here the issue seems to occur with passwords that have at least 12 characters.

**Comment by fviale** [comment]
Ok, thanks for the precision.

**Comment by fviale** [comment]
I experienced the same issue on my Windows 10 machine, with a password containing 5 letters and 3 digits, using latest version ProActiveAgent-7.23-standalone.

**Comment by fviale** [comment]
I tried different combination of passwords and always get the same error message.

**Comment by fviale** [comment]
The issue seems to appear randomly, depending on the machine, each time for Windows 10 operating system, maybe as well on Windows 8.

A workaround fortunately exist:

Right click on the installation program, e.g. ProActiveAgent-7.y.z-standalone-x64-setup.exe ), then **Properties**, then **Compatibility**, then check **Execute this program in compatibility mode for**, then choose **Windows XP Service Pack 3**

**Comment by fviale** [comment]
I stumbled on the same issue, even the workaround (compatibility mode 7, or XP) does not fix the problem

**Comment by fviale** [comment]
I was using a wrong version, close the issue for now
